{"variants":[{"paths":["\/documentation\/watchrtc_sdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/watchrtc_sdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/RTCStatsReport","doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTC","doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTCConfig"]},{"title":"Protocols","identifiers":["doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/DebugLoggerProtocol","doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/RtcDataProvider"]},{"title":"Structures","identifiers":["doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/RTCStat","doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTCSessionDescription"]},{"title":"Enumerations","identifiers":["doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/EventType","doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/LogLevel"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"WatchRTC_SDK","title":"WatchRTC_SDK","symbolKind":"module","role":"collection","modules":[{"name":"WatchRTC_SDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/RtcDataProvider":{"role":"symbol","title":"RtcDataProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RtcDataProvider"}],"abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/RtcDataProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RtcDataProvider"}],"url":"\/documentation\/watchrtc_sdk\/rtcdataprovider"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/WatchRTC_SDKVersionString":{"role":"symbol","title":"WatchRTC_SDKVersionString","fragments":[{"kind":"identifier","text":"WatchRTC_SDKVersionString"}],"abstract":[{"type":"text","text":"Project version string for WatchRTC."}],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTC_SDKVersionString","kind":"symbol","type":"topic","url":"\/documentation\/watchrtc_sdk\/watchrtc_sdkversionstring"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK":{"role":"collection","title":"WatchRTC_SDK","abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK","kind":"symbol","type":"topic","url":"\/documentation\/watchrtc_sdk"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/RTCStat":{"role":"symbol","title":"RTCStat","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RTCStat"}],"abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/RTCStat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RTCStat"}],"url":"\/documentation\/watchrtc_sdk\/rtcstat"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/watchrtc_sdk\/loglevel"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/WatchRTC_SDKVersionNumber":{"role":"symbol","title":"WatchRTC_SDKVersionNumber","fragments":[{"kind":"identifier","text":"WatchRTC_SDKVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for WatchRTC."}],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTC_SDKVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/watchrtc_sdk\/watchrtc_sdkversionnumber"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/DebugLoggerProtocol":{"role":"symbol","title":"DebugLoggerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugLoggerProtocol"}],"abstract":[{"type":"text","text":"Used by WatchRTC to log debug, info and error messages. Implement this protocol in order to provide custom debug logger behavior (e.g. logging to file, custom formatting, etc.)"}],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/DebugLoggerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DebugLoggerProtocol"}],"url":"\/documentation\/watchrtc_sdk\/debugloggerprotocol"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/WatchRTCConfig":{"role":"symbol","title":"WatchRTCConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchRTCConfig"}],"abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTCConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatchRTCConfig"}],"url":"\/documentation\/watchrtc_sdk\/watchrtcconfig"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/RTCStatsReport":{"role":"symbol","title":"RTCStatsReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RTCStatsReport"}],"abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/RTCStatsReport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RTCStatsReport"}],"url":"\/documentation\/watchrtc_sdk\/rtcstatsreport"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/WatchRTC":{"role":"symbol","title":"WatchRTC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchRTC"}],"abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatchRTC"}],"url":"\/documentation\/watchrtc_sdk\/watchrtc"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/WatchRTCSessionDescription":{"role":"symbol","title":"WatchRTCSessionDescription","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchRTCSessionDescription"}],"abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTCSessionDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatchRTCSessionDescription"}],"url":"\/documentation\/watchrtc_sdk\/watchrtcsessiondescription"},"doc://com.sdk.ios.watchrtc.WatchRTC-SDK-iOS/documentation/WatchRTC_SDK/EventType":{"role":"symbol","title":"EventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventType"}],"abstract":[],"identifier":"doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/EventType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventType"}],"url":"\/documentation\/watchrtc_sdk\/eventtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTC_SDKVersionNumber","doc:\/\/com.sdk.ios.watchrtc.WatchRTC-SDK-iOS\/documentation\/WatchRTC_SDK\/WatchRTC_SDKVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}